name: 01-Building-Blocks
on: push

jobs:
  echo-helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: echo helloworld
        run: echo "Hello World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Step for success
        run: |
          echo "I will work hard and succeed"
          exit 0
      - name: Say goodbye
        run: echo "Good bye!"
