name: 01-Building-Blocks
on: push

jobs:
  echo-helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: echo helloworld
        run: echo "Hello World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: fail on purpose
        run: |
          echo "I will fail"
          exit 1
      - name: Say goodbye
        run: echo "Good bye!"
